<a href="https://colab.research.google.com/github/Supernoahy/data-science-toolkit/blob/main/Tutorial_03_NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np


In [4]:
#2*2 NumPy array (fixed values)
array_2x2 =np.array([[1,2],[3,4]])
print("Task 1-2*2 Array:")
print(array_2x2)
print("shape:",array_2x2.shape)

Task 1-2*2 Array:
[[1 2]
 [3 4]]
shape: (2, 2)


In [5]:
# Random 3x4 array (integers between 0 and 50)
random_3x4 = np.random.randint(low=0, high=51, size=(3, 4))  # size=(rows, columns)
print("\nTask 2 - Random 3x4 Array:")
print(random_3x4)
print("Shape:", random_3x4.shape)


Task 2 - Random 3x4 Array:
[[32 18 48 41]
 [43 12 30 19]
 [31 27 38 25]]
Shape: (3, 4)


In [6]:
# Array of ones (3x3)
ones_array = np.ones(shape=(3, 3), dtype=int)  # dtype=int to avoid floats
# Array of zeros (2x5)
zeros_array = np.zeros(shape=(2, 5), dtype=int)

print("\nTask 3 - Array of Ones (3x3):")
print(ones_array)
print("\nTask 3 - Array of Zeros (2x5):")
print(zeros_array)


Task 3 - Array of Ones (3x3):
[[1 1 1]
 [1 1 1]
 [1 1 1]]

Task 3 - Array of Zeros (2x5):
[[0 0 0 0 0]
 [0 0 0 0 0]]


In [7]:
# Random 6x3 array (floats between 0 and 1)
random_6x3 = np.random.rand(6, 3)
# Transpose the array
transposed_array = random_6x3.T  # Equivalent to np.transpose(random_6x3)

print("\nTask 4 - Original Random 6x3 Array:")
print(random_6x3)
print("Shape (original):", random_6x3.shape)
print("\nTask 4 - Transposed Array (3x6):")
print(transposed_array)
print("Shape (transposed):", transposed_array.shape)


Task 4 - Original Random 6x3 Array:
[[0.38609907 0.36596776 0.06677167]
 [0.84784111 0.5221766  0.47250912]
 [0.78140987 0.81852778 0.06501609]
 [0.77578447 0.62732909 0.93375735]
 [0.11382248 0.29277632 0.27371525]
 [0.58956433 0.69878824 0.53121129]]
Shape (original): (6, 3)

Task 4 - Transposed Array (3x6):
[[0.38609907 0.84784111 0.78140987 0.77578447 0.11382248 0.58956433]
 [0.36596776 0.5221766  0.81852778 0.62732909 0.29277632 0.69878824]
 [0.06677167 0.47250912 0.06501609 0.93375735 0.27371525 0.53121129]]
Shape (transposed): (3, 6)


In [9]:
# Define dimensions (n, p, m)
n = 2
p = 3
m = 4

# Create two random arrays (n×p and p×m)
array_np = np.random.rand(n, p)  # 2x3 array
array_pm = np.random.rand(p, m)  # 3x4 array

# Compute dot product (use np.dot() or @ operator)
dot_product = np.dot(array_np, array_pm)  # Equivalent to array_np @ array_pm

print("\nTask 5 - First Array (n×p = 2×3):")
print(array_np)
print("\nTask 5 - Second Array (p×m = 3×4):")
print(array_pm)
print("\nTask 5 - Dot Product (n×m = 2×4):")
print(dot_product)
print("Shape (dot product):", dot_product.shape)  # Should be (2, 4)


Task 5 - First Array (n×p = 2×3):
[[0.97792284 0.4331782  0.53110234]
 [0.26772706 0.64718412 0.47784544]]

Task 5 - Second Array (p×m = 3×4):
[[0.4458122  0.68102513 0.78298664 0.64815787]
 [0.97052169 0.58165328 0.62876101 0.41595823]
 [0.08805179 0.60983837 0.56328378 0.52062895]]

Task 5 - Dot Product (n×m = 2×4):
[[0.90314328 1.24183613 1.33722741 1.09053967]
 [0.78953736 0.85017411 0.88571344 0.69151114]]
Shape (dot product): (2, 4)
